List<String> wisdomData = [
  "All the suffering, stress and addiction comes from not realizing you already are what you are looking for. \n-Jon Kabat-Zinn-",
  "The secret of getting ahead is getting started. \n-Mark Twain-",
  "I used to be a chain smoker, but I realized that it was taking a toll on my health. I decided to quit smoking for the sake of my family and my fans.\n- actor Rajinikanth",
  "It is in your moments of decision that your destiny is shaped. \n-Tony Robbins-",
  "Believe you can and you’re halfway there. \n-Theodore Roosevelt-",
  "The surest way not to fail is to determine to succeed. \n-Richard Brinsley Sheridan-",
  "Our strength grows out of our weakness. \n-Ralph Waldo Emerson-",
  "I'm a big believer in that if you stop smoking, you'll live longer. And I think that if you don't smoke, you might actually see grandchildren. \n-Bill Murray",
  "Smoking is related to practically every terrible thing that can happen to you. \n- Dr. Richard Hurt",
  "The biggest mistake a person can make is to start smoking, and the biggest mistake they can make is not to quit.\n- Dr. Benjamin Rush",
  "Smoking is hateful to the nose, harmful to the brain, and dangerous to the lungs.\n- King James I",
  "Quitting smoking is easy, I've done it hundreds of times. \n- Mark Twain",
  "The best way to quit smoking is to never start.\n- Anonymous",
  "You must quit smoking. I recommend taking up a second bad habit to take your mind off the first.\n- John Oliver",
  "Quitting smoking is like hitting a reset button on your life.\n- Anonymous",
  "I quit smoking in December. I'm really happy about that.\n- David Bowie",
  "Smoking kills. If you're killed, you've lost a very important part of your life.\n- Brooke Shields",
  "The pain of quitting smoking is temporary, but the benefits are lifelong.\n- Anonymous",
  "Quitting smoking is the best gift you can give to yourself.\n- Anonymous",
  "Quitting smoking is not easy, but it is worth it.\n- Anonymous",
  "You don't have to see the whole staircase, just take the first step towards quitting smoking.\n- Anonymous",
  "Quitting smoking is a journey, not a destination.\n- Anonymous",
  "Quitting smoking is not just about breaking a bad habit, it's about reclaiming your life.\n- Anonymous",
  "The only way to quit smoking is to stop making excuses and start taking action.\n- Anonymous",
  "Quitting smoking is a sign of strength, not weakness.\n- Anonymous",
  "The first step towards quitting smoking is to believe that you can do it.\n- Anonymous",
  "Quitting smoking is hard, but not quitting could be harder.\n- Anonymous",
  "Quitting smoking is not easy, but it's necessary. It's one of the best things you can do for your health.",
  "Smoking is not just harmful to you, but also to the people around you. I didn't want to be the cause of anyone's suffering.",
  "I feel much better now that I have quit smoking. I have more energy, and I can focus better.",
  "If you're a smoker, I urge you to quit. It's never too late to start taking care of your health.",
  "I used to smoke a lot, but I have quit now. It's been six years, and it feels great. I feel like a new person.\n- actor surya",
  "I realized that smoking was not only harming me, but also the people around me. I didn't want to be the cause of someone else's illness.",
  "Quitting smoking is not easy, but it's possible. You just need to have the determination and willpower to do it.",
  "I feel healthier, happier, and more energetic since I quit smoking. It's the best decision I ever made.",
  "Your life is in your hands, to make of it what you choose.\n– Anonymous",
  "The key is focusing on the positive. Build up the good things in your life",
  "Giving up doesn't always mean you are weak, sometimes it means you are strong enough and smart enough to let go. \n– Anonymous",
  "We cannot, in a moment, get rid of habits of a lifetime.\n- Mahatma Gandhi",
  "Our strength grows out of our weakness.\n– Ralph Waldo Emerson",
  "The purpose of our lives is to be happy.\n- Dalai Lama",
  "The biggest adventure you can ever take is to live the life of your dreams.\n- Oprah Winfrey",
  "Be the change you wish to see in the world.\n- Mahatma Gandhi",
  "Your life does not get better by chance, it gets better by change.\n- Jim Rohn",
  "Life is not a problem to be solved, but a reality to be experienced.\n- Soren Kierkegaard",
  "A healthy outside starts from the inside.\n- Robert Urich",
  "Good health and good sense are two of life's greatest blessings.\n- Publilius Syrus",
  "Investing in your health is the best investment you can make.\n- Bethenny Frankel",
  "Healthy citizens are the greatest asset any country can have.\n- Winston Churchill",
  "Take care of your body. It's the only place you have to live.\n- Jim Rohn",
  "Don't watch the clock; do what it does. Keep going.\n- Sam Levenson",
  "Believe you can and you're halfway there.\n- Theodore Roosevelt",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.\n- Winston Churchill",
  "Success is not how high you have climbed, but how you make a positive difference to the world.\n- Roy T. Bennett",
  "The future belongs to those who believe in the beauty of their dreams.\n- Eleanor Roosevelt",
  "If you want to live a happy life, tie it to a goal, not to people or things.\n- Albert Einstein",
  "A dream doesn't become reality through magic; it takes sweat, determination and hard work.\n- Colin Powell",
  "Don't let anyone tell you that you can't do something. Follow your dreams, and prove them wrong.\n- Will Smith",
  "Dream big and dare to fail.\n- Norman Vaughan",
  "Dreams are the touchstones of our character.\n- Henry David Thoreau",
  "All our dreams can come true, if we have the courage to pursue them.\n- Walt Disney",
  "Dreams are the seedlings of reality.\n- Napoleon Hill",
];
