List<Map> allYoga = [
  {
    'src': "assets/images/yoga/thunderbolt.png",
    'yogaName': "Thunderbolt Pose",
    'description':
        "Thunderbolt pose, also known as Vajrasana in Sanskrit, is a seated yoga posture that involves kneeling on the floor and sitting back on the heels, with the hands resting on the knees or thighs. Here are some of the benefits of practicing thunderbolt pose regularly:\n\n\tImproves digestion: Thunderbolt pose is believed to help improve digestion by increasing blood flow to the digestive organs and improving overall gut health.\n\n\tPromotes calmness and mental clarity: Thunderbolt pose is a grounding posture that can help calm the mind and reduce stress and anxiety. Practicing this posture regularly can help promote mental clarity and a sense of inner peace.\n\n\tImproves posture: By gently stretching the spine and opening up the chest, thunderbolt pose can help improve posture and reduce tension in the shoulders and neck.\n\n\tImproves blood circulation: Thunderbolt pose can help improve blood circulation to the legs and feet, which can be especially beneficial for individuals who spend long hours sitting or standing.\n\n\tHelps with ankle and knee pain: Kneeling in thunderbolt pose can help stretch and strengthen the muscles around the ankles and knees, which can be helpful for individuals with chronic pain or discomfort in these areas.\n\n\tMay help with weight loss: Some studies suggest that practicing thunderbolt pose regularly may help with weight loss by improving metabolism and reducing food cravings.",
  },
  {
    'src': "assets/images/yoga/cobra.png",
    'yogaName': "Cobra Pose",
    'description':
        "Cobra pose (Bhujangasana) is a popular yoga posture that offers a number of physical and mental health benefits. Here are some of the benefits of practicing cobra pose regularly:\n\n\tOpens the chest: By stretching the chest and lungs, cobra pose can help improve breathing capacity and reduce tension in the chest and shoulders.  \n\n\tRelieves stress and fatigue: Cobra pose is known to help reduce stress and fatigue by releasing tension in the body and improving blood flow. It can also help stimulate the adrenal glands, which can improve energy levels.\n\n\tHelps with digestion: The gentle pressure on the abdomen in cobra pose can help improve digestion and relieve constipation.\n\n\tTherapeutic for menstrual irregularities: Cobra pose is also considered therapeutic for menstrual irregularities, as it can help stimulate the reproductive organs and regulate menstrual cycles.",
  },
  {
    'src': "assets/images/yoga/bow.png",
    'yogaName': "Bow Pose",
    'description':
        "Bow pose, also known as Dhanurasana in Sanskrit, is a yoga posture that involves lying on the stomach and lifting the legs and upper body off the ground while holding onto the ankles with the hands. Here are some of the benefits of practicing bow pose regularly:\n\n\tStrengthens the back: Bow pose is a powerful back strengthening posture that can help improve posture and alleviate back pain.\n\n\tImproves flexibility: By stretching the muscles in the chest, abdomen, hips, and thighs, bow pose can improve overall flexibility and range of motion.\n\n\tBoosts digestion: Bow pose can help stimulate the digestive organs and improve digestion, making it a beneficial pose for individuals with digestive issues.\n\n\tRelieves stress and fatigue: Bow pose is believed to help reduce stress and fatigue by improving blood flow and releasing tension in the body.\n\n\tImproves respiratory function: By opening up the chest and lungs, bow pose can improve respiratory function and increase oxygen intake.\n\n\tHelps with menstrual discomfort: Bow pose can be therapeutic for menstrual discomfort by stimulating the reproductive organs and reducing tension in the pelvic area",
  },
  {
    'src': "assets/images/yoga/cat.png",
    'yogaName': "Cat-Cow Pose",
    'description':
        "Cat-cow pose, also known as Marjaryasana/Bitilasana in Sanskrit, is a gentle yoga sequence that involves alternating between arching the back (cow pose) and rounding the spine (cat pose).Here are some of the ways cat-cow pose can indirectly help with quitting smoking:\n\n\tReduces stress: Smoking is often used as a coping mechanism for stress, anxiety, and other negative emotions. By reducing stress levels, cat-cow pose can help individuals find healthier ways to manage their emotions and reduce their dependence on smoking.\n\n\tImproves breathing: Smoking can damage the lungs and make it difficult to breathe. Cat-cow pose involves deep breathing and can help improve respiratory function, which can be especially beneficial for individuals with respiratory issues.\n\n\tEnhances mindfulness: Cat-cow pose requires concentration and focus, which can help individuals become more aware of their thoughts, emotions, and behaviors. This increased mindfulness can help individuals identify triggers for smoking and develop strategies for avoiding or coping with them.\n\n\tImproves mood: Smoking can cause fluctuations in mood, leading to irritability, anxiety, and depression. Cat-cow pose can help improve mood by releasing tension in the body and promoting relaxation.",
  },
];
